### ISSUE TITLE
Gitkeep file in the root

### ISSUE THREAD

**Issue by BrandonRomano** [carrot/sprout-gcore#5]
The file `root/.gitkeep`... Is this needed for some reason in sprout?

Otherwise we should probably remove it, so it doesn't get added in all new projects.

**Comment by roideuniverse** [comment]
@BrandonRomano : I guess we can remove it. I think sprout keeps it intentionally to keep the empty folder `root`, but since our folder is no longer empty - we could remove it.

**Comment by BrandonRomano** [comment]
Gotcha, I can remove this myself!  PR incoming !

**Comment by roideuniverse** [comment]
:+1:
